version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: euronet-postgres
    restart: always
    environment:
      POSTGRES_DB: euronetdb
      POSTGRES_USER: euronet
      POSTGRES_PASSWORD: euronet123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: euronet-backend:1.0
    container_name: euronet-backend
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/euronetdb
      SPRING_DATASOURCE_USERNAME: euronet
      SPRING_DATASOURCE_PASSWORD: euronet123
    ports:
      - "8080:8080"

volumes:
  postgres_data:
